// <auto-generated />
using System;
using FoodOrder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrder.Data.Migrations
{
    [DbContext(typeof(FoodDbContext))]
    [Migration("20251120202239_AddedOrderToFoodModel")]
    partial class AddedOrderToFoodModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodOrder.Entities.Models.Food", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = "1e7c8b8e-4a9d-4bc4-9f18-1cc6f30edc11",
                            Name = "Pizza",
                            Price = 10.0,
                            Slug = ""
                        },
                        new
                        {
                            Id = "3d47c7a1-8f0f-4cb1-9b92-f5235eb3f83e",
                            Name = "Hamburger",
                            Price = 12.0,
                            Slug = ""
                        });
                });

            modelBuilder.Entity("FoodOrder.Entities.Models.Ingredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CaloriePer100Gramms")
                        .HasColumnType("float");

                    b.Property<string>("FoodId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Gramms")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = "b5a1c94d-19d4-4e16-a60b-d093c8bcd451",
                            CaloriePer100Gramms = 350.0,
                            FoodId = "1e7c8b8e-4a9d-4bc4-9f18-1cc6f30edc11",
                            Gramms = 50,
                            Name = "Cheese"
                        },
                        new
                        {
                            Id = "8b32f9a0-59ae-417a-9c28-f6fa1f2e55ca",
                            CaloriePer100Gramms = 20.0,
                            FoodId = "1e7c8b8e-4a9d-4bc4-9f18-1cc6f30edc11",
                            Gramms = 30,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = "c27479a1-07ad-4a63-8c4b-0b7035e8dcc8",
                            CaloriePer100Gramms = 250.0,
                            FoodId = "1e7c8b8e-4a9d-4bc4-9f18-1cc6f30edc11",
                            Gramms = 100,
                            Name = "Dough"
                        },
                        new
                        {
                            Id = "e2f1a3cd-11ea-4c92-8461-6053b9a9f9c2",
                            CaloriePer100Gramms = 250.0,
                            FoodId = "3d47c7a1-8f0f-4cb1-9b92-f5235eb3f83e",
                            Gramms = 120,
                            Name = "Beef Patty"
                        },
                        new
                        {
                            Id = "0ffb5dc5-6a51-4ed7-94a5-41b15b5e0e8b",
                            CaloriePer100Gramms = 280.0,
                            FoodId = "3d47c7a1-8f0f-4cb1-9b92-f5235eb3f83e",
                            Gramms = 80,
                            Name = "Bun"
                        },
                        new
                        {
                            Id = "f9482b0d-3ebe-434e-8bd0-44c446a7a5b0",
                            CaloriePer100Gramms = 330.0,
                            FoodId = "3d47c7a1-8f0f-4cb1-9b92-f5235eb3f83e",
                            Gramms = 40,
                            Name = "Cheese Slice"
                        });
                });

            modelBuilder.Entity("FoodOrder.Entities.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodOrder.Entities.Models.Food", b =>
                {
                    b.HasOne("FoodOrder.Entities.Models.Order", "Order")
                        .WithMany("Food")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodOrder.Entities.Models.Ingredient", b =>
                {
                    b.HasOne("FoodOrder.Entities.Models.Food", "Food")
                        .WithMany("Ingredients")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Food");
                });

            modelBuilder.Entity("FoodOrder.Entities.Models.Food", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("FoodOrder.Entities.Models.Order", b =>
                {
                    b.Navigation("Food");
                });
#pragma warning restore 612, 618
        }
    }
}
